services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: neuroscholar-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend/data:/app/data

      # Keep uploaded PDFs outside the container
      - ./backend/uploads:/app/uploads

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: neuroscholar-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped